version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  
  web:
    build: .
    command: python manage.py runserver 5.9.198.249:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - postgres
volumes:
  db_data:
